apiVersion: v1
kind: Service
metadata:
  name: employee-master-app
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
  selector:
    app: employee-master-app
